name: check

on: [pull_request]

env:
  VITE_API_KEY: secrets.API_KEY
  VITE_APP_ID: secrets.APP_ID
  VITE_AUTH_DOMAIN: secrets.AUTH_DOMAIN
  VITE_DATABASE_URL: secrets.DATABASE_URL
  VITE_MESSAGING_SENDER_ID: secrets.MESSAGING_SENDER_ID
  VITE_MEASUREMENT_ID: secrets.MEASUREMENT_ID
  VITE_PROJECT_ID: secrets.PROJECT_ID
  VITE_STORAGE_BUCKET: secrets.STORAGE_BUCKET

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: yarn install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: yarn test
        uses: CultureHQ/actions-yarn@master
        with:
          args: test
      - name: yarn build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build
  build_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "10"
      - name: Install
        working-directory: ./functions
        run: npm install
      - name: Lint
        working-directory: ./functions
        run: npm run lint
      - name: Build
        working-directory: ./functions
        run: npm run build
  deploy_for_preview:
    runs-on: ubuntu-latest
    needs: [build, build_functions]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: yarn install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: yarn build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build
        env:
          VITE_API_KEY: secrets.API_KEY
          VITE_APP_ID: secrets.APP_ID
          VITE_AUTH_DOMAIN: secrets.AUTH_DOMAIN
          VITE_DATABASE_URL: secrets.DATABASE_URL
          VITE_MESSAGING_SENDER_ID: secrets.MESSAGING_SENDER_ID
          VITE_MEASUREMENT_ID: secrets.MEASUREMENT_ID
          VITE_PROJECT_ID: secrets.PROJECT_ID
          VITE_STORAGE_BUCKET: secrets.STORAGE_BUCKET
      - name: Firebase Preview Deploy
        if: ${{ github.repository_owner == 'tegehoge' }}
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 10d
          projectId: leaction
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
