name: firebase-deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    environment: Production Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install yarn
        run: npm install -g yarn
      - run: yarn install
      - run: yarn test
      - name: Make dotenv
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_VITE_API_KEY: ${{ secrets.API_KEY }}
          envkey_VITE_APP_ID: ${{ secrets.APP_ID }}
          envkey_VITE_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
          envkey_VITE_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_VITE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
          envkey_VITE_MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
          envkey_VITE_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          envkey_VITE_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
      - run: yarn build
      - name: npm install for firebase functions
        working-directory: ./functions
        run: npm install
      - name: Firebase Production Deploy
        run: yarn deploy --token=${{ secrets.FIREBASE_TOKEN }}
